/** Internal catalog URLs for blog backlinks and CTAs. */
export const CATALOG_LINKS = {
  all: '/products',
  event: '/products?category_id=3',
  cradle: '/products?category_id=3&subcategory_id=10',
  swings: '/products?category_id=3&subcategory_id=13',
  chairs: '/products?category_id=3&subcategory_id=11',
  decor: '/products?category_id=3&subcategory_id=9',
  props: '/products?category_id=3&subcategory_id=12',
  backdrop: '/products?category_id=4',
  birthday: '/products?category_id=5',
  babyProps: '/products?category_id=6',
  kidsToys: '/products?category_id=7',
  games: '/products?category_id=8',
  camping: '/products?category_id=1',
  appliances: '/products?category_id=2',
  howItWorks: '/how-it-works',
  delivery: '/delivery-info',
  faq: '/faq',
  contact: '/contact',
};
